# Договор
contract:
  # номер договора
  number: ПМД-АС/01
  # дата заключения договора
  date: 11.01.2024
# Заказ в рамках договора
order:
  # номер заказа (заявки)
  number: 6
  # дата выставления заявки
  date: 05.06.2024
  # согласованный сторонами срок выполнения заказа
  deadline: 28.06.2024
  # фактический период, за который заказ был выполнен
  work:
    start: 05.06.2024
    end: 26.06.2024
  # перечень работ в рамках заказа
  jobs:
    - name: Участие Исполнителя в разработке системы для моделирования распределения жителей по территории мегаполиса
      quantity: 4.0
      price: 32000.0
    - name: Участие Исполнителя в проектировании программной реализации системы авторизации в геоинформационной системе мониторинга снегоуборки города
      quantity: 5.0
      price: 24000.0
    - name: Участие Исполнителя в доработке системы построения маршрутов с использованием данных геолокационных систем
      quantity: 3.5
      price: 32000.0
# счет
bill:
  number: 06-ПМД-АС/01
  date: 26.07.2024
# акт
act:
  number: 06-ПМД-АС/01
  date: 26.07.2024
# имена файлов для генерируемых документов
processing:
  act:
    template: act_template.docx
    dest: "{str((datetime.datetime.now().strftime('%Y%m%d')))}_Акт_Заказ_N{int(act['number'][:2])}_ИИИ_Рога_и_копыта.docx"
  order:
    template: order_template.docx
    dest: "{str((datetime.datetime.now().strftime('%Y%m%d')))}_Заявка_N{order['number']}_ИИИ_Рога_и_копыта.docx"
